name: 03 - workflow runners
on: push
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
         -  name: Shows OS
            run: echo "This job is running on" $RUNNER_OS
    
    windows-echo:
        runs-on: windows-latest
        steps:
         -  name: Shows OS
            shell: bash
            run: echo "This job is running on" $RUNNER_OS
    mac-echo:
        runs-on: macos-latest
        steps:
         -  name: Shows OS
            run: echo "This job is running on" $RUNNER_OS