name: 06 - contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on:
    workflow_dispatch:
    # push:
    #     branches:
    #         - main
inputs:
    debug:
        type: boolean
        default: false
jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Event name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "Actor: ${{ github.actor }}"
                echo "SHA: ${{ github.sha }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "RunId: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"
            - name: Retrieve Variable
              run: |
                echo "Variable value: ${{ vars.MY_VAR }}"