name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on:
    workflow_dispatch:
      inputs:
        debug:
            type: boolean
            default: false


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] print startup data'
              if: ${{ inputs.debug }}
              run: |
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}"

            - name: '[debug] print when triggered from main'
              if: ${{ inputs.debug && github.ref  == 'refs/heads/main'}}
              run: echo "I am triggered from main"

            - name: Greetings
              run: | 
                echo 'Hello world!'
