name: 07 - Using Expressions

on:
    push:
        branches:
            - main
    workflow_dispatch:
      inputs:
        debug:
            type: boolean
            default: false


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Data
              if: inputs.debug == true
              run: |
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}"

            - name: Branch details
              if: ${{ github.ref }} == 'refs/heads/main' && inputs.debug == true
              run: echo "I am triggered from main"

            - name: Greeting
              run: echo "Hello world!"