name: 12 - Working with Outputs

on: 
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.GITHUB_OUTPUT}}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo $GITHUB_OUTPUT
            - name: Build
              id: build
              run: echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
    deploy:
        runs-on: ubuntu-latest
        needs:
            - build
        if: ${{ $status == susccess }}
        steps:
            - name: Deploy
              run: echo "Deploying"