name: 15 - Working with Matrices

on:
    workflow_dispatch:

jobs:
    backwards-compatibility:
        name: ${{matrix.os}} - ${{matrix.node-version}}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [18.x,20.x,21.x]
                os: 
                 - ubuntu-latest
                 - windows-latest
                include:
                  - os: ubuntu-latest
                    node-version: 16.x
                  - os: windows-latest
                    node-version: 21.x
                    tag: experimental
                
        steps:
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Setup Node1
              if: (matrix.node-version == '21.x' && matrix.tag == 'experimental')
              # run: exit 1
              run: echo ${{ matrix.node-version}}'-'${{matrix.tag}}
            - name: Perform some Tests
              run: |
                echo "Running tests on OS ${{ matrix.os}} and NodeJS ${{ matrix.node-version }}"
                sleep 10
            - name: Upload test results
              run: echo "Upload test results.."
    
    include-example:
      name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{matrix.opacity}}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          color:
            - red
            - green
          shape:
            - square
            - circle
          size: [small, large]
          include:
            - color: red
              opacity: 75
            - shape: circle
              opacity: 100
            - color: red
              shape: triangle
            - opacity: 50
          exclude:
            - opacity: 75
            - color: red
      steps:
        - name: Dummy step
          run: | 
            echo ${{matrix.color}}"-"${{matrix.shape}}"-"${{matrix.size}}"-"${{matrix.opacity}}
