name: 16 - working with environments

on:
    workflow_dispatch:
            
jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: deploying to staging
              run: |
                echo "Deploying to staging"
    e2e-testing:
        runs-on: ubuntu-latest
        needs: 
            - deploy-staging
        steps:
            - name: testing
              run: echo "Running e2e testings"
    deploy-prod:
        runs-on: ubuntu-latest
        environment: prod
        needs: e2e-testing
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: Echo-vars
              run: echo ${{env.my-env-value}}


                
