name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - ${{inputs.target-env}}

on:
    workflow_dispatch:
        inputs:
            target-env:
                type: choice
                description: which environment do you want setup node
                default: dev
                options:
                    - dev
                    - prod
env:
    working-directory: 17-custom-actions/react-app

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{env.working-directory}}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                node-version: 20.x
                target-env: ${{inputs.target-env}}
                working-directory: ${{env.working-directory}}
            - name: Test
              run: npm run test
            - name: Build
              run: npm run build
