name: '17 - 2 - Custom Actions - JS'
run-name: 17 - 2 - Custom Actions - JS | BB - ${{ inputs.base-branch }} TB - ${{ inputs.target-branch }} WD - ${{ inputs.working-dir }}
on:
    workflow_dispatch:
      inputs:
        base-branch:
          type: string
        target-branch:
          type: string
        working-dir:
          type: string
        debug:
          type: string

jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Check for dependency version
              uses: ./.github/actions/js-dependency-update
            
